
CREATE TABLE [dbo].[Player]
(
	[PlayerId] INT primary key,
    [PlayerName] VARCHAR(24),
    [Pos] VARCHAR(5),
    [Age] INT,
    [FG] NUMERIC(3, 1),
    [FGA] NUMERIC(3, 1),
    [FG%] NUMERIC(10, 9),
    [3P] NUMERIC(2, 1),
    [3PA] NUMERIC(3, 1),
    [3P%] NUMERIC(4, 3),
    [2P] NUMERIC(3, 1),
    [2PA] NUMERIC(3, 1),
    [2P%] NUMERIC(4, 3),
    [eFG%] NUMERIC(4, 3),
    [FT] NUMERIC(3, 1),
    [FTA] NUMERIC(3, 1),
    [FT%] NUMERIC(4, 3),
    [ORB] NUMERIC(2, 1),
    [DRB] NUMERIC(3, 1),
    [TRB] NUMERIC(3, 1),
    [AST] NUMERIC(3, 1),
    [STL] NUMERIC(2, 1),
    [BLK] NUMERIC(2, 1),
    [TOV] NUMERIC(2, 1),
    [PF] NUMERIC(2, 1),
    [PTS] NUMERIC(3, 1),
    [PER] NUMERIC(3, 1),
    [TS%] NUMERIC(4, 3),
    [3PAr%] NUMERIC(4, 3),
    [FTr] NUMERIC(4, 3),
    [ORB%] NUMERIC(4, 1),
    [DRB%] NUMERIC(3, 1),
    [TRB%] NUMERIC(3, 1),
    [AST%] NUMERIC(3, 1),
    [STL%] NUMERIC(3, 1),
    [BLK%] NUMERIC(3, 1),
    [TOV%] NUMERIC(3, 1),
    [USG%] NUMERIC(3, 1),
    [OWS] NUMERIC(3, 1),
    [DWS] NUMERIC(2, 1),
    [WS] NUMERIC(3, 1),
    [WS_48] NUMERIC(4, 3),
    [OBPM] NUMERIC(3, 1),
    [DBPM] NUMERIC(3, 1),
    [BPM] NUMERIC(3, 1),
    [VORP] NUMERIC(2, 1)
)